substitutions:
  device_name: ComfoAir
  filter_time: 5s
  filter_send_every: '1'
  filter_window_size: '3'
  can_tx_pin: GPIO22
  can_rx_pin: GPIO19

packages:
  remote_package:
    url: https://github.com/dan-s-github/zehnder-comfoair-esp32/packages
    ref: main
    files: 
      - canbus.yml
      - binary_sensors.yml
      - button.yml
      - select.yml
      - sensors.yml
      - switch.yml
      - text_sensors.yml
      - fan.yml
      - climate.yml

esphome:
  name: "zehnder-comfoair-q350"
  friendly_name: Zehnder ComfoAir Q350
  comment: Zehnder ComfoAir Q350

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
  logs:
    canbus: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "5wqUYCw5MwKhuU/c7KL2+JCCe9JIe57CmTuhYhQ/BYM="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-D67654"
    password: "9fe5gQPRfKeL"

captive_portal:

external_components:
  - source: github://dan-s-github/zehnder-comfoair-esp32
    components: [ zehnder_comfoair_q  ]

# See docs: https://github.com/michaelarnauts/aiocomfoconnect/blob/master/docs/PROTOCOL-PDO.md
zehnder_comfoair_q:
  id: comfoair
  request_ids: [16, 49, 54, 55, 65, 66, 67, 81, 82, 117, 118, 119, 120, 121, 122, 128, 129, 130, 192, 209, 210, 211, 212, 212, 213, 214, 215, 216, 217, 218, 220, 221, 227, 274, 275, 276, 277, 278, 290, 291, 292, 293, 294]


