substitutions:
  project_version: "1.0.0"

# # Sensors for ESP version and WIFI information
text_sensor:
  # Installed version
  - platform: template
    name: "Device Version"
    id: device_version
    icon: "mdi:label-outline"
    entity_category: diagnostic
    lambda: |-
      return {"${project_version}"};
    update_interval: 6h
  # ESPHome version
  - platform: version
    hide_timestamp: true
    name: 'ESPHome Version'
  # IP address and connected SSID
  - platform: wifi_info
    ip_address:
      name: 'IP Address'
      icon: mdi:wifi
    ssid:
      name: 'SSID'
      icon: mdi:wifi-strength-2

sensor:
  # Uptime
  - platform: uptime
    name: Uptime Sensor
  # WiFi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 120s